name: Update Google Sheets

on:
  repository_dispatch:
    types: [update-sheets]

jobs:
  update-sheets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update Google Sheets
        run: python update_sheets.py
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}

      - name: Debug Information
        if: failure()
        run: |
          echo "GCP_SA_KEY is set: ${{ secrets.GCP_SA_KEY != '' }}"
          echo "GOOGLE_SHEET_ID is set: ${{ secrets.GOOGLE_SHEET_ID != '' }}"
