name: Update Google Sheets

on:
  push:
    branches:
      - master

jobs:
  update-sheets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update Google Sheets
        env:
          SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: python update_sheets.py
